--**********************************************Ecommerce Store(MSWKH)**********************************************************

--Instance Details
select instance_name, status, host_name, version from v$instance;
-------------------------------------------------------Tablespaces-----------------------------------------------------
--ECOMMERCE_DATA TABLESPACE
CREATE TABLESPACE ecommerce_data
DATAFILE 'C:\Oracle_21c\oradata\ORCL\orclpdb\ecommerce_data01.dbf'
SIZE 200M AUTOEXTEND ON;

--ECOMMERCE_INDEX 
CREATE TABLESPACE ecommerce_index
DATAFILE 'C:\Oracle_21c\oradata\ORCL\orclpdb\ecommerce_index01.dbf'
SIZE 100M AUTOEXTEND ON;
--Show table is related to which tablespace
SELECT table_name, tablespace_name
FROM user_tables;
--Check Tablespaces Status
SELECT tablespace_name, status
FROM user_tablespaces;

--Moving Tables to "ecommerce_data Tablespace" 
ALTER TABLE customer MOVE TABLESPACE ecommerce_data;
ALTER TABLE products MOVE TABLESPACE ecommerce_data;
ALTER TABLE orders MOVE TABLESPACE ecommerce_data;
ALTER TABLE cart MOVE TABLESPACE ecommerce_data;
ALTER TABLE order_items MOVE TABLESPACE ecommerce_data;

------------------------------------------------------Tables-----------------------------------------------------------
-- Customer table 
CREATE TABLE customer (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20)
);
select * from customer;

-- Products table 
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(200),
    price NUMBER(10,2) NOT NULL
);

INSERT INTO products (name, description, price) VALUES ('Laptop', 'Electronics - High performance laptop', 85000);
INSERT INTO products (name, description, price) VALUES ('Smartphone', 'Electronics - Latest 5G smartphone', 55000);
INSERT INTO products (name, description, price) VALUES ('Bluetooth Earbuds', 'Electronics - Wireless earbuds with mic', 6000);
INSERT INTO products (name, description, price) VALUES ('Gaming Keyboard', 'Electronics - RGB mechanical keyboard', 4500);
INSERT INTO products (name, description, price) VALUES ('Smartwatch', 'Electronics - Health monitoring smartwatch', 9500);

INSERT INTO products (name, description, price) VALUES ('Men T-Shirt', 'Fashion - 100% cotton premium shirt', 1200);
INSERT INTO products (name, description, price) VALUES ('Women Handbag', 'Fashion - Stylish leather handbag', 3500);
INSERT INTO products (name, description, price) VALUES ('Sneakers', 'Fashion - Comfortable running sneakers', 4300);
INSERT INTO products (name, description, price) VALUES ('Hoodie', 'Fashion - Winter warm hoodie', 2500);

INSERT INTO products (name, description, price) VALUES ('Electric Kettle', 'Home Appliances - 1.5L stainless steel kettle', 2800);
INSERT INTO products (name, description, price) VALUES ('Air Fryer', 'Home Appliances - Oil-free cooking fryer', 14500);
INSERT INTO products (name, description, price) VALUES ('Vacuum Cleaner', 'Home Appliances - High suction vacuum', 9000);
INSERT INTO products (name, description, price) VALUES ('LED Lamp', 'Home Appliances - Rechargeable LED lamp', 1600);

INSERT INTO products (name, description, price) VALUES ('Face Cream', 'Beauty - Hydrating daily moisturizer', 700);
INSERT INTO products (name, description, price) VALUES ('Perfume', 'Beauty - Long-lasting fragrance', 2200);
INSERT INTO products (name, description, price) VALUES ('Hair Dryer', 'Beauty - Compact foldable dryer', 1800);
COMMIT;
ALTER TABLE products ADD category VARCHAR2(50);
UPDATE products SET category = 'Electronics' WHERE name = 'Laptop';
UPDATE products SET category = 'Electronics' WHERE name = 'Smartphone';
UPDATE products SET category = 'Electronics' WHERE name = 'Bluetooth Earbuds';
UPDATE products SET category = 'Electronics' WHERE name = 'Gaming Keyboard';
UPDATE products SET category = 'Electronics' WHERE name = 'Smartwatch';

UPDATE products SET category = 'Fashion' WHERE name = 'Men T-Shirt';
UPDATE products SET category = 'Fashion' WHERE name = 'Women Handbag';
UPDATE products SET category = 'Fashion' WHERE name = 'Sneakers';
UPDATE products SET category = 'Fashion' WHERE name = 'Hoodie';

UPDATE products SET category = 'Home Appliances' WHERE name = 'Electric Kettle';
UPDATE products SET category = 'Home Appliances' WHERE name = 'Air Fryer';
UPDATE products SET category = 'Home Appliances' WHERE name = 'Vacuum Cleaner';
UPDATE products SET category = 'Home Appliances' WHERE name = 'LED Lamp';

UPDATE products SET category = 'Beauty & Personal Care' WHERE name = 'Face Cream';
UPDATE products SET category = 'Beauty & Personal Care' WHERE name = 'Perfume';
UPDATE products SET category = 'Beauty & Personal Care' WHERE name = 'Hair Dryer';
select * from products;

-- Cart table (linked to customer and products)
CREATE TABLE cart (
    cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES customer(customer_id) ON DELETE CASCADE,
    product_id NUMBER REFERENCES products(product_id) ON DELETE CASCADE,
    quantity NUMBER DEFAULT 1
);
select * from cart;
SELECT index_name, table_name, status
FROM user_indexes
WHERE index_name = 'SYS_C008294';
ALTER INDEX SYS_C008294 REBUILD;


DESC cart;    --show all attributes of table
--DROP TABLE cart CASCADE CONSTRAINTS;

-- Orders table (to track orders placed by customer)
CREATE TABLE orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER REFERENCES customer(customer_id),
    order_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(10,2)
);
select * from orders;

-- Order items table (products included in an order)
CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id NUMBER REFERENCES products(product_id),
    quantity NUMBER DEFAULT 1,
    price NUMBER(10,2) -- price at time of purchase
);
select * from order_items;

--SELECT index_name, table_name, status
--FROM user_indexes
--WHERE index_name IN ('SYS_C008305', 'SYS_C008294', 'SYS_C008285', 'SYS_C008295');
--ALTER INDEX SYS_C008305 REBUILD;
--ALTER INDEX SYS_C008294 REBUILD;
--ALTER INDEX SYS_C008285 REBUILD;
--ALTER INDEX SYS_C008295 REBUILD;

--Show all your tables
SELECT table_name FROM user_tables;
--Show all columns of Products
SELECT column_name, data_type, data_length 
FROM user_tab_columns 
WHERE table_name = 'PRODUCTS';
--Show tables with user name(owner)
SELECT table_name, owner 
FROM all_tables
WHERE table_name IN ('CUSTOMER','PRODUCTS','CART','ORDERS','ORDER_ITEMS');

------------------------------------------------------Integrity Constraints---------------------------------------------------
--Email format CHECK
ALTER TABLE customer
ADD CONSTRAINT chk_customer_email
CHECK (email LIKE '%@%');

SELECT constraint_name, table_name
FROM user_constraints
WHERE table_name = 'CUSTOMER';

--One product once per customer in cart
/*ALTER TABLE cart
ADD CONSTRAINT uq_cart_customer_product
UNIQUE (customer_id, product_id);
ALTER TABLE cart
DROP CONSTRAINT uq_cart_customer_product;*/

--Total amount should not be negative
ALTER TABLE orders
ADD CONSTRAINT chk_order_total
CHECK (total_amount >= 0);
--CHECK ALL CONSTRAINTS (Verification)
SELECT table_name, constraint_name, constraint_type
FROM user_constraints
WHERE table_name IN
('CUSTOMER','PRODUCTS','CART','ORDERS','ORDER_ITEMS')
ORDER BY table_name;

----------------------------------------------------------Indexes---------------------------------------------------
--single column index
CREATE INDEX idx_customer_phone
ON customer(phone)
TABLESPACE ecommerce_index;

--Composite index
CREATE INDEX idx_order_customer_date
ON orders(customer_id, order_date)
TABLESPACE ecommerce_index;
--Index Range Plan
EXPLAIN PLAN FOR SELECT * FROM orders WHERE customer_id = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

--VERIFY INDEX LOCATION
SELECT index_name, table_name, tablespace_name
FROM user_indexes
WHERE table_name = 'CUSTOMER';


---------------------------------------------------------Views----------------------------------------------------------
--Customer Orders View
CREATE VIEW Customer_Orders AS
SELECT c.name, o.order_id, o.total_amount
FROM customer c
JOIN orders o ON c.customer_id = o.customer_id;
--Orders with high amount(verify view)
SELECT *
FROM Customer_Orders
WHERE total_amount > 5000;


--Product Sales View
CREATE VIEW ProductSales AS
SELECT p.name, SUM(oi.quantity) AS TotalSold
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
GROUP BY p.name;
--verify(Top selling products)
SELECT name, TotalSold
FROM ProductSales
ORDER BY TotalSold DESC;

select view_name from user_views;
----------------------------------------------------JOINS (REPORT QUERIES)------------------------------------------------
--Customer + Orders Join
SELECT c.name AS CustomerName,
       o.order_id AS OrderID,
       o.order_date AS OrderDate,
       o.total_amount AS TotalAmount
FROM customer c
JOIN orders o ON c.customer_id = o.customer_id;

--Order Details Join (4-table join)
SELECT c.name AS CustomerName,
       p.name AS ProductName,
       oi.quantity AS Quantity,
       oi.price AS PriceAtPurchase,
       o.order_date AS OrderDate
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN customer c ON o.customer_id = c.customer_id
JOIN products p ON oi.product_id = p.product_id;

---------------------------------------------------DENORMALIZED REPORT QUERY-----------------------------------------------
SELECT 
    o.order_id,
    c.name AS customer_name,
    c.phone,
    COUNT(oi.order_item_id) AS total_products,
    SUM(oi.quantity) AS total_items,
    SUM(oi.quantity * oi.price) AS bill_amount
FROM orders o
JOIN customer c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
GROUP BY 
    o.order_id,
    c.name,
    c.phone;


------------------------------------------------SEGMENTS & EXTENTS (CHECK ONLY)----------------------------------------------
SELECT segment_name, segment_type, bytes/1024 AS KB
FROM user_segments;

SELECT extent_id, bytes/1024 AS KB
FROM user_extents
WHERE segment_name = 'PRODUCTS';

select segment_name, COUNT(*) AS Extents from user_extents where segment_name IN ('CUSTOMER', 'PRODUCTS', 'ORDERS', 'ORDER_ITEMS') 
GROUP BY segment_name;

-----------------------------------------------------BACKUP TABLE-----------------------------------------------------------
CREATE TABLE Products_Backup AS SELECT * FROM products;
--VERIFY
SELECT table_name
FROM user_tables
WHERE table_name = 'PRODUCTS_BACKUP';
--MIN / MAX values compare (quick test)
SELECT MIN(product_id), MAX(product_id) FROM products;
SELECT MIN(product_id), MAX(product_id) FROM Products_Backup;

----------------------------------------------SAVEPOINT + ROLLBACK TO SAVEPOINT---------------------------------------------
SAVEPOINT sp1;
UPDATE products SET price = price + 2000;
ROLLBACK TO sp1;
select * from products;

--Helps DBAs monitor undo tablespace usage, transaction activity, and detect potential issues.
SELECT begin_time, end_time, undoblks, txncount, maxquerylen
FROM v$undostat
ORDER BY end_time DESC;
--Current tablespace the DB is using
SELECT name, value
FROM v$parameter
WHERE name = 'undo_tablespace';

--New Undo Creation
CREATE UNDO TABLESPACE undo_new
DATAFILE 'undo_new01.dbf'
SIZE 500M AUTOEXTEND ON;
--Switch to new UNDO
ALTER SYSTEM SET UNDO_TABLESPACE = undo_new;

--Check Undo Status, Retention
SELECT tablespace_name, status, retention
FROM dba_tablespaces
WHERE contents = 'UNDO';


--------------------------------------------------SEQUENCE + TRIGGERS------------------------------------------------------
--Sequence
CREATE SEQUENCE order_seq START WITH 6000 INCREMENT BY 1;
--Verify
SELECT sequence_name, last_number
FROM user_sequences
WHERE sequence_name = 'ORDER_SEQ';

--Trigger
CREATE OR REPLACE TRIGGER trg_orderitems_id
BEFORE INSERT ON order_items
FOR EACH ROW
BEGIN
    :NEW.order_item_id := order_seq.NEXTVAL;
END;
/
--check trigger name, status
SELECT trigger_name, status
FROM user_triggers
WHERE trigger_name = 'TRG_ORDERITEMS_ID';
--insert into order_items
INSERT INTO order_items(order_item_id, product_id, quantity)
VALUES (1001, 10, 2);
COMMIT;
--verify
SELECT order_item_id, order_id, product_id, quantity
FROM order_items
ORDER BY order_item_id DESC;


-------------------------------------------------FUNCTIONS & PROCEDURES---------------------------------------------------
--Function
CREATE OR REPLACE FUNCTION CountItems(p_orderid NUMBER)
RETURN NUMBER
AS
    totalItems NUMBER;
BEGIN
    SELECT SUM(quantity)
    INTO totalItems
    FROM order_items
    WHERE order_id = p_orderid;

    RETURN totalItems;
END;
/
--Check Validity
SELECT object_name, status
FROM user_objects
WHERE object_type = 'FUNCTION'
AND object_name = 'COUNTITEMS';

SELECT order_id FROM orders;

SELECT CountItems(42) FROM dual;

---------------------Procedure
--pl/sql block with exception handling
CREATE OR REPLACE PROCEDURE AddProduct
(pid NUMBER, pname VARCHAR2, pprice NUMBER)
AS
BEGIN
    INSERT INTO products (product_id, name, price, category)
    VALUES (pid, pname, pprice, 'General');

    COMMIT;

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Product ID already exists!');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/
--Verify
BEGIN
    AddProduct(202, 'Wall Clocks', 1500);
END;
/
SELECT * 
FROM products 
WHERE product_id=202;


-----------------------------------------------------Customer Details--------------------------------------------------
--Customer Profile (Specific Customer)
SELECT customer_id, name, email, phone
FROM customer
WHERE customer_id = 1;

--Customer Summary Report (One Query 💎)
SELECT 
    c.customer_id,
    c.name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(oi.quantity) AS total_items,
    SUM(oi.quantity * oi.price) AS total_amount
FROM customer c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
WHERE c.customer_id = 23
GROUP BY c.customer_id, c.name;

--Customer ne Konse Products Buy Kiye (Most Bought)
SELECT 
    p.name AS product_name,
    SUM(oi.quantity) AS total_quantity
FROM orders o
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE o.customer_id = 1
GROUP BY p.name
ORDER BY total_quantity DESC;

--Complete Details of specific order(Invoice Style)
SELECT 
    c.name AS customer_name,
    o.order_id,
    o.order_date,
    p.name AS product_name,
    oi.quantity,
    oi.price,
    (oi.quantity * oi.price) AS item_total
FROM orders o
JOIN customer c ON o.customer_id = c.customer_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
WHERE c.customer_id = 1
AND o.order_id = 43;

--Query Optimization Using WHERE + LIMIT (Top Products)
SELECT name, price
FROM products
WHERE price > 2000
ORDER BY price DESC
FETCH FIRST 5 ROWS ONLY;

--Composite query
select order_id, customer_id, order_date, total_amount from orders where customer_id=1 AND order_date > DATE '2025-12-21';

--Partition
CREATE TABLE products_part (
    product_id NUMBER,
    name VARCHAR2(100),
    price NUMBER(10,2),
    category VARCHAR2(50)
)
PARTITION BY LIST (category) (
    PARTITION electronics VALUES ('Electronics'),
    PARTITION fashion VALUES ('Fashion'),
    PARTITION home_appliances VALUES ('Home Appliances'),
    PARTITION beauty VALUES ('Beauty & Personal Care'),
    PARTITION other VALUES (DEFAULT)
);
SELECT table_name, partitioned
FROM user_tables
WHERE table_name = 'PRODUCTS_PART';

SELECT table_name, partition_name
FROM user_tab_partitions
WHERE table_name = 'PRODUCTS_PART';


-----------------------------------------------------------------------------------
--pl/sql blocks
SET SERVEROUTPUT ON SIZE 1000000;
--Cursor
BEGIN
    FOR rec IN (SELECT name FROM products ORDER BY name) LOOP
        DBMS_OUTPUT.PUT_LINE('Product: ' || rec.name);
    END LOOP;
END;
/

--Exception handling-->Print price or error
SET SERVEROUTPUT ON SIZE 1000000;

DECLARE
    v_price NUMBER;
BEGIN
    SELECT price INTO v_price 
    FROM products 
    WHERE product_id = 22;
    -- print the price if found
    DBMS_OUTPUT.PUT_LINE('Price of product 22 is: ' || v_price);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Product not found!');
END;
/





